apiVersion: v1
kind: Service
metadata:
  name: java-mysql
  labels:
    app: java
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 31088
  selector:
    app: java
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: java
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: java-mysql
  labels:
    app: java
spec:
  selector:
    matchLabels:
      app: java
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: java
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
